export function getElements() {
  return {
    levelList: document.getElementById("levelList"),
    activeTitle: document.getElementById("activeTitle"),
    xpTotal: document.getElementById("xpTotal"),
    currentLevel: document.getElementById("currentLevel"),
    completionTotal: document.getElementById("completionTotal"),
    streakTotal: document.getElementById("streakTotal"),
    mentalModel: document.getElementById("mentalModel"),
    phaseLabel: document.getElementById("phaseLabel"),
    weekMap: document.getElementById("weekMap"),
    weekPhase: document.getElementById("weekPhase"),
    weekTitle: document.getElementById("weekTitle"),
    weekStory: document.getElementById("weekStory"),
    visibleWin: document.getElementById("visibleWin"),
    weekLevel: document.getElementById("weekLevel"),
    lessonList: document.getElementById("lessonList"),
    companyLabel: document.getElementById("companyLabel"),
    challengePrompt: document.getElementById("challengePrompt"),
    schemaGrid: document.getElementById("schemaGrid"),
    queryInput: document.getElementById("queryInput"),
    runButton: document.getElementById("runButton"),
    solutionButton: document.getElementById("solutionButton"),
    feedbackBox: document.getElementById("feedbackBox"),
    solutionBox: document.getElementById("solutionBox"),
    sqlStatus: document.getElementById("sqlStatus"),
    reviewList: document.getElementById("reviewList"),
    reviewButton: document.getElementById("reviewButton"),
    reviewStatus: document.getElementById("reviewStatus"),
    bossTitle: document.getElementById("bossTitle"),
    bossPrompt: document.getElementById("bossPrompt"),
    bossMonth: document.getElementById("bossMonth"),
    bossButton: document.getElementById("bossButton"),
    badgeGrid: document.getElementById("badgeGrid"),
    badgeCount: document.getElementById("badgeCount"),
    resetButton: document.getElementById("resetButton")
  };
}
